version: "3.7"
services:
  hivemq:
    image: hivemq/hivemq4
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8884:8884"
      - "8083:8083"
    volumes:
      - ./config.xml:/opt/hivemq/conf/config.xml
